version: "3.8"
services:
  python-bridge:
    build:
      context: .
      dockerfile: Dockerfile.python
    ports:
      - "5555:5555"
      - "8000:8000"
    environment:
      - BRIDGE_SERVER_PORT=5555
      - BRIDGE_CLIENT_PORT=5556
      - JWT_SECRET=test_secret
    command: python run_server.py

  node-bridge:
    build:
      context: .
      dockerfile: Dockerfile.node
    ports:
      - "5556:5556"
      - "8001:8001"
    depends_on:
      - python-bridge
